import javax.swing.JOptionPane;
import javax.swing.table.*;
public class adminpage extends javax.swing.JFrame {
        public static int count_location = 0;
        public static int count_time = 0;
        public static String[][]location = new String[10][1];
        public static String[][]time = new String[21][3];
        String A;       
           
        methodgraph graph = new methodgraph();
 
    public adminpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        bt_backadmin = new javax.swing.JButton();
        bt_addsendername = new javax.swing.JButton();
        txt_sendername = new javax.swing.JTextField();
        combo_receivername = new javax.swing.JComboBox<>();
        combo_sendername = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_sendername = new javax.swing.JTable();
        txt_time = new javax.swing.JTextField();
        bt_addtocombo = new javax.swing.JButton();
        bt_clearaddsendername = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_time = new javax.swing.JTable();
        bt_addtime = new javax.swing.JButton();
        bt_openselectmenu = new javax.swing.JButton();
        combobox_menu = new javax.swing.JComboBox<>();
        bt_viewshopadmin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_backadmin.setBackground(new java.awt.Color(255, 153, 153));
        bt_backadmin.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        bt_backadmin.setText("Logout");
        bt_backadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backadminActionPerformed(evt);
            }
        });
        getContentPane().add(bt_backadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 680, 170, 50));

        bt_addsendername.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        bt_addsendername.setText("add");
        bt_addsendername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addsendernameActionPerformed(evt);
            }
        });
        getContentPane().add(bt_addsendername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 100, -1));

        txt_sendername.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        txt_sendername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sendernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_sendername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 270, 40));

        combo_receivername.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        combo_receivername.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "." }));
        combo_receivername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_receivernameActionPerformed(evt);
            }
        });
        getContentPane().add(combo_receivername, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 180, 40));

        combo_sendername.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        combo_sendername.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "." }));
        combo_sendername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_sendernameActionPerformed(evt);
            }
        });
        getContentPane().add(combo_sendername, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 180, 40));

        table_sendername.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        table_sendername.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "location"
            }
        ));
        jScrollPane2.setViewportView(table_sendername);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 410, 220));

        txt_time.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        getContentPane().add(txt_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 230, 40));

        bt_addtocombo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        bt_addtocombo.setText("add to combo box");
        bt_addtocombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addtocomboActionPerformed(evt);
            }
        });
        getContentPane().add(bt_addtocombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 180, 30));

        bt_clearaddsendername.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        bt_clearaddsendername.setText("clear");
        bt_clearaddsendername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clearaddsendernameActionPerformed(evt);
            }
        });
        getContentPane().add(bt_clearaddsendername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 100, 30));

        table_time.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        table_time.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender name", "Receiver name", "Time"
            }
        ));
        jScrollPane4.setViewportView(table_time);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 410, 250));

        bt_addtime.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        bt_addtime.setText("add time");
        bt_addtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addtimeActionPerformed(evt);
            }
        });
        getContentPane().add(bt_addtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 140, 40));

        bt_openselectmenu.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        bt_openselectmenu.setText("select");
        bt_openselectmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_openselectmenuActionPerformed(evt);
            }
        });
        getContentPane().add(bt_openselectmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, 140, 40));

        combobox_menu.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        combobox_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_menuActionPerformed(evt);
            }
        });
        getContentPane().add(combobox_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 230, 40));

        bt_viewshopadmin.setBackground(new java.awt.Color(204, 204, 255));
        bt_viewshopadmin.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        bt_viewshopadmin.setText("view shop");
        bt_viewshopadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_viewshopadminActionPerformed(evt);
            }
        });
        getContentPane().add(bt_viewshopadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 680, 170, 50));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel2.setText("to");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/03adminpage.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_backadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backadminActionPerformed
        new welcome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_backadminActionPerformed

    private void bt_addsendernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addsendernameActionPerformed
        DefaultTableModel model = (DefaultTableModel)table_sendername.getModel();
        location[count_location][0] = txt_sendername.getText();
        for (int i = count_location;i <= count_location; i++){
            String row[] = new String[location[i].length];
            for (int j=0; j<location[i].length; j++){
                row[j] = location[i][j];
            }
            model.addRow(row);
        }
        count_location = count_location+1; 
    }//GEN-LAST:event_bt_addsendernameActionPerformed

    private void txt_sendernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sendernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sendernameActionPerformed

    private void bt_clearaddsendernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clearaddsendernameActionPerformed
        txt_sendername.setText("");
    }//GEN-LAST:event_bt_clearaddsendernameActionPerformed

    private void bt_addtocomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addtocomboActionPerformed
        combo_sendername.addItem(adminpage.location[0][0]);
        combo_sendername.addItem(adminpage.location[1][0]);
        combo_sendername.addItem(adminpage.location[2][0]);
        combo_sendername.addItem(adminpage.location[3][0]);
        combo_sendername.addItem(adminpage.location[4][0]);       
        combo_receivername.addItem(adminpage.location[0][0]);
        combo_receivername.addItem(adminpage.location[1][0]);
        combo_receivername.addItem(adminpage.location[2][0]);
        combo_receivername.addItem(adminpage.location[3][0]);
        combo_receivername.addItem(adminpage.location[4][0]);       
        combobox_menu.addItem(adminpage.location[0][0]);
        combobox_menu.addItem(adminpage.location[1][0]);
        combobox_menu.addItem(adminpage.location[2][0]);
        combobox_menu.addItem(adminpage.location[3][0]);
        combobox_menu.addItem(adminpage.location[4][0]);     
    }//GEN-LAST:event_bt_addtocomboActionPerformed

    private void combo_sendernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_sendernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_sendernameActionPerformed

    private void combo_receivernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_receivernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_receivernameActionPerformed

    private void bt_openselectmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_openselectmenuActionPerformed
        A = (String) combobox_menu.getSelectedItem();
        if(A.equals(adminpage.location[0][0])){          
            new menulo01().setVisible(true);
        }
        else if(A.equals(adminpage.location[1][0])){
            new menulo02().setVisible(true);
        }
        else if(A.equals(adminpage.location[2][0])){
            new menulo03().setVisible(true);
        }
        else if(A.equals(adminpage.location[3][0])){
            new menulo04().setVisible(true);
        }
        else if(A.equals(adminpage.location[4][0])){
            new menulo05().setVisible(true);
        }
    }//GEN-LAST:event_bt_openselectmenuActionPerformed

    private void bt_addtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addtimeActionPerformed
        //add time
        DefaultTableModel model = (DefaultTableModel)table_time.getModel();
        time[count_time][0] = (String)combo_sendername.getSelectedItem();
        time[count_time][1] = (String)combo_receivername.getSelectedItem();
        time[count_time][2] = txt_time.getText();
        for (int i = count_time;i <= count_time; i++){
            String row[] = new String[time[i].length];
            for (int j=0; j<time[i].length; j++){
                row[j] = time[i][j];
            }
            model.addRow(row);
        }
       count_time = count_time+1;
       
       
        
    }//GEN-LAST:event_bt_addtimeActionPerformed

    private void combobox_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_menuActionPerformed

    private void bt_viewshopadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_viewshopadminActionPerformed
        new userpage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_viewshopadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        
          
             
   
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addsendername;
    private javax.swing.JButton bt_addtime;
    private javax.swing.JButton bt_addtocombo;
    private javax.swing.JButton bt_backadmin;
    private javax.swing.JButton bt_clearaddsendername;
    private javax.swing.JButton bt_openselectmenu;
    private javax.swing.JButton bt_viewshopadmin;
    private javax.swing.JComboBox<String> combo_receivername;
    private javax.swing.JComboBox<String> combo_sendername;
    private javax.swing.JComboBox<String> combobox_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable table_sendername;
    private javax.swing.JTable table_time;
    private javax.swing.JTextField txt_sendername;
    private javax.swing.JTextField txt_time;
    // End of variables declaration//GEN-END:variables
}
