import javax.swing.table.*;
public class menulo02 extends javax.swing.JFrame {
        public static int count_menu02 = 0;
        public static String[][]menu02 = new String[10][2];
    
    public menulo02() {
        initComponents();
        restaurant2.setText(adminpage.location[1][0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_menu02 = new javax.swing.JTable();
        restaurant2 = new javax.swing.JLabel();
        txt_addprice02 = new javax.swing.JTextField();
        txt_menu02 = new javax.swing.JTextField();
        bt_addmenu02 = new javax.swing.JButton();
        bt_clear02 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jButton1.setText("close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 710, 100, 40));

        jTable_menu02.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jTable_menu02.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu", "Price"
            }
        ));
        jScrollPane2.setViewportView(jTable_menu02);
        if (jTable_menu02.getColumnModel().getColumnCount() > 0) {
            jTable_menu02.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 420, 210));

        restaurant2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        restaurant2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restaurant2.setText("-");
        getContentPane().add(restaurant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 380, -1));

        txt_addprice02.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(txt_addprice02, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 230, 38));

        txt_menu02.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txt_menu02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_menu02ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_menu02, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 230, 38));

        bt_addmenu02.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        bt_addmenu02.setText("add");
        bt_addmenu02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addmenu02ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_addmenu02, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 90, 38));

        bt_clear02.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        bt_clear02.setText("clear");
        bt_clear02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clear02ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_clear02, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 90, 38));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/03menu2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_menu02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_menu02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_menu02ActionPerformed

    private void bt_addmenu02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addmenu02ActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable_menu02.getModel();
        menu02[count_menu02][0] = txt_menu02.getText();
        menu02[count_menu02][1] = txt_addprice02.getText();
        for (int i = count_menu02;i <= count_menu02; i++){
            String row[] = new String[menu02[i].length];
            for (int j=0; j<menu02[i].length; j++){
                row[j] = menu02[i][j];
            }
            model.addRow(row);
        }
        count_menu02 = count_menu02+1;

    }//GEN-LAST:event_bt_addmenu02ActionPerformed

    private void bt_clear02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clear02ActionPerformed
        txt_menu02.setText("");
        txt_addprice02.setText("");
    }//GEN-LAST:event_bt_clear02ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menulo02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menulo02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menulo02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menulo02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menulo02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addmenu02;
    private javax.swing.JButton bt_clear02;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_menu02;
    private javax.swing.JLabel restaurant2;
    private javax.swing.JTextField txt_addprice02;
    private javax.swing.JTextField txt_menu02;
    // End of variables declaration//GEN-END:variables
}
