import javax.swing.table.*;
public class menulo03 extends javax.swing.JFrame {
        public static int count_menu03 = 0;
        public static String[][]menu03 = new String[10][2];
   
    public menulo03() {
        initComponents();
        restaurant3.setText(adminpage.location[2][0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bt_addmenu03 = new javax.swing.JButton();
        txt_addprice03 = new javax.swing.JTextField();
        bt_clear03 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_menu03 = new javax.swing.JTable();
        txt_menu03 = new javax.swing.JTextField();
        restaurant3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jButton1.setText("close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 710, 100, 40));

        bt_addmenu03.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        bt_addmenu03.setText("add");
        bt_addmenu03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addmenu03ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_addmenu03, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 94, 38));

        txt_addprice03.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(txt_addprice03, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 240, 38));

        bt_clear03.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        bt_clear03.setText("clear");
        bt_clear03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clear03ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_clear03, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 90, 40));

        jTable_menu03.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jTable_menu03.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable_menu03);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 420, 210));

        txt_menu03.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txt_menu03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_menu03ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_menu03, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 240, 38));

        restaurant3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        restaurant3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restaurant3.setText("-");
        getContentPane().add(restaurant3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 390, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/03menu3.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_addmenu03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addmenu03ActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable_menu03.getModel();
        menu03[count_menu03][0] = txt_menu03.getText();
        menu03[count_menu03][1] = txt_addprice03.getText();
        for (int i = count_menu03;i <= count_menu03; i++){
            String row[] = new String[menu03[i].length];
            for (int j=0; j<menu03[i].length; j++){
                row[j] = menu03[i][j];
            }
            model.addRow(row);
        }
        count_menu03 = count_menu03+1;

    }//GEN-LAST:event_bt_addmenu03ActionPerformed

    private void txt_menu03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_menu03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_menu03ActionPerformed

    private void bt_clear03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clear03ActionPerformed
        txt_menu03.setText("");
        txt_addprice03.setText("");
    }//GEN-LAST:event_bt_clear03ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menulo03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menulo03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menulo03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menulo03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menulo03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addmenu03;
    private javax.swing.JButton bt_clear03;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_menu03;
    private javax.swing.JLabel restaurant3;
    private javax.swing.JTextField txt_addprice03;
    private javax.swing.JTextField txt_menu03;
    // End of variables declaration//GEN-END:variables
}
