import javax.swing.table.*;   
public class menulo04 extends javax.swing.JFrame {
        public static int count_menu04 = 0;
        public static String[][]menu04 = new String[10][2];
   
    public menulo04() {
        initComponents();
        restaurant4.setText(adminpage.location[3][0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        bt_addmenu04 = new javax.swing.JButton();
        txt_addprice04 = new javax.swing.JTextField();
        bt_clear04 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_menu04 = new javax.swing.JTable();
        txt_menu04 = new javax.swing.JTextField();
        restaurant4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jButton1.setText("close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 710, 100, 40));

        bt_addmenu04.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        bt_addmenu04.setText("add");
        bt_addmenu04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addmenu04ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_addmenu04, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 94, 38));

        txt_addprice04.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(txt_addprice04, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 240, 38));

        bt_clear04.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        bt_clear04.setText("clear");
        bt_clear04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clear04ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_clear04, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 90, 40));

        jTable_menu04.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jTable_menu04.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable_menu04);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 420, 210));

        txt_menu04.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txt_menu04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_menu04ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_menu04, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 240, 38));

        restaurant4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        restaurant4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restaurant4.setText("-");
        getContentPane().add(restaurant4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 390, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/03menu4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_addmenu04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addmenu04ActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable_menu04.getModel();
        menu04[count_menu04][0] = txt_menu04.getText();
        menu04[count_menu04][1] = txt_addprice04.getText();
        for (int i = count_menu04;i <= count_menu04; i++){
            String row[] = new String[menu04[i].length];
            for (int j=0; j<menu04[i].length; j++){
                row[j] = menu04[i][j];
            }
            model.addRow(row);
        }
        count_menu04 = count_menu04+1;

    }//GEN-LAST:event_bt_addmenu04ActionPerformed

    private void bt_clear04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clear04ActionPerformed
        txt_menu04.setText("");
        txt_addprice04.setText("");
    }//GEN-LAST:event_bt_clear04ActionPerformed

    private void txt_menu04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_menu04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_menu04ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menulo04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menulo04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menulo04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menulo04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menulo04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addmenu04;
    private javax.swing.JButton bt_clear04;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_menu04;
    private javax.swing.JLabel restaurant4;
    private javax.swing.JTextField txt_addprice04;
    private javax.swing.JTextField txt_menu04;
    // End of variables declaration//GEN-END:variables
}
