import javax.swing.JOptionPane;
public class welcome extends javax.swing.JFrame {

    public welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_loginwel = new javax.swing.JButton();
        bt_discountcode = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_loginwel.setBackground(new java.awt.Color(204, 255, 204));
        bt_loginwel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        bt_loginwel.setText("Login");
        bt_loginwel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginwelActionPerformed(evt);
            }
        });
        getContentPane().add(bt_loginwel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 700, 140, 50));

        bt_discountcode.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        bt_discountcode.setForeground(new java.awt.Color(204, 0, 0));
        bt_discountcode.setText("discount code click here.");
        bt_discountcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_discountcodeMouseClicked(evt);
            }
        });
        getContentPane().add(bt_discountcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 200, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/01welcome.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_loginwelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginwelActionPerformed
        new login().setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_bt_loginwelActionPerformed

    private void bt_discountcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_discountcodeMouseClicked
        
        new discount().setVisible(true); 
    }//GEN-LAST:event_bt_discountcodeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
          
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_discountcode;
    private javax.swing.JButton bt_loginwel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
